### ISSUE TITLE
BOOST_PP_EMPTY(...)

### ISSUE THREAD

**Issue by vinipsmaker2** [boostorg/preprocessor#34]
Could you change current definition from:

```c
#define BOOST_PP_EMPTY()
```

to:

```c
#define BOOST_PP_EMPTY(...)
```

This will make some of my patterns easier without the need to define my own `BOOST_PP_EMPTY` (which is what I'm doing right now).

**Comment by eldiener** [comment]
The Boost VMD library has BOOST_VMD_EMPTY(...), which does exactly what you want, but it is understandable that you would want the same functionality in Boost PP, especially because it has been decided that for the next Boost release the Boost PP library, like the current Boost VMD library, assumes variadic macro support in the preprocessor. So I will make the change in Boost PP in the 'develop' branch and then merge it to 'master' after it has been tested. Thanks for bringing this issue up.

**Comment by vinipsmaker2** [comment]
I was unaware of Boost.VMD. Thank you.

**Comment by eldiener** [comment]
I have decided to not make the change for the Boost preprocessor library. The reason for this as that the change can break compilation for those using the Visual C++ default preprocessor and a variadic version of BOOST_PP_EMPTY. The reason for the need for those using the Visual C++ default preprocessor to change their code if using a variadic version of BOOST_PP_EMPTY is explained in the documentation for BOOST_VMD_EMPTY in the topic "Generating emptiness and identity" in the VMD docs. Please use the BOOST_VMD_EMPTY macro, or the BOOST_VMD_IDENTITY macro, to achieve what you want to do. It is in the header file `boost/vmd/identity.hpp` and does not depend on any other functionality in the VMD library. If you have any further questions about its use, please ask.

**Comment by vinipsmaker2** [comment]
I'm already using `BOOST_VMD_EMPTY`. Thank you.
